
package GenerarArchivo;

import ParserClasses.Header;
import ParserClasses.Import;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Date;

/**
 *
 * @author Paulette
 */
public class GenerarArchivo {

    public GenerarArchivo() {
    }
    
    public void CrearArchivo() throws IOException
    {
      
        try{
        String contenido = "";
        File file = new File("src\\mycup\\MyParser.java");
       
        if (!file.exists()) 
        {
            file.createNewFile();
	}
       
        //HEADER
           contenido="//----------------------------------------------------\n";
           contenido+="//The Following Code was generated by MyCup Proyecto Compi. II \n";
           Date date = new Date();
           contenido+="//"+date+"\n";
           contenido+="//----------------------------------------------------\n";
         
            FileWriter fw = new FileWriter(file.getAbsoluteFile());
            BufferedWriter bw = new BufferedWriter(fw);
            bw.write(contenido);
            bw.close();

            System.out.println("MyParser.java Creado");

            }catch (Exception e){
                System.err.println("Error Grammar->CrearArchivo(): " + e.getMessage());
            }
        

    }
    
}
